/* eslint-disable @typescript-eslint/no-unused-expressions */
[
  {
    id: 1,
    productName: "Glock 19 Gen 5",
    category: "Handgun",
    brand: "Glock",
    price: 499.99,
    inStock: true,
    onSale: false,
    rating: 4.8,
    caliber: "9mm",
    weight: "670g",
    material: "Polymer",
    image: "/images/glock19.jpg",
    description:
      "The Glock 19 Gen 5 is a compact 9mm handgun perfect for personal defense.",
    reviews: 150,
    SKU: "GLK-19G5-9MM",
    quantity: 25,
  },
  {
    id: 2,
    productName: "Remington 870 Tactical",
    category: "Shotgun",
    brand: "Remington",
    price: 399.99,
    inStock: true,
    onSale: true,
    rating: 4.6,
    caliber: "12 gauge",
    weight: "3kg",
    material: "Steel",
    image: "/images/remington870.jpg",
    description:
      "The Remington 870 Tactical is known for its versatility and reliability in self-defense.",
    reviews: 95,
    SKU: "REM-870T-12G",
    quantity: 12,
  },
  {
    id: 3,
    productName: "Winchester 5.56 NATO Ammunition",
    category: "Ammunition",
    brand: "Winchester",
    price: 12.99,
    inStock: true,
    onSale: false,
    rating: 4.9,
    caliber: "5.56mm",
    weight: "62gr",
    material: "Brass casing",
    image: "/images/winchester556.jpg",
    description:
      "Winchester 5.56 NATO ammunition offers reliable performance for target shooting and defense.",
    reviews: 300,
    SKU: "WIN-556NATO-62GR",
    quantity: 100,
  },
  {
    id: 4,
    productName: "Sig Sauer P320 Full-Size",
    category: "Handgun",
    brand: "Sig Sauer",
    price: 549.99,
    inStock: false,
    onSale: false,
    rating: 4.7,
    caliber: "9mm",
    weight: "833g",
    material: "Polymer and Stainless Steel",
    image: "/images/sigp320.jpg",
    description:
      "The Sig Sauer P320 is a modular and versatile full-size handgun for military and law enforcement.",
    reviews: 220,
    SKU: "SIG-P320-9MM",
    quantity: 0,
  },
  {
    id: 5,
    productName: "Federal Premium .308 Winchester",
    category: "Ammunition",
    brand: "Federal",
    price: 25.99,
    inStock: true,
    onSale: false,
    rating: 4.9,
    caliber: ".308 Win",
    weight: "168gr",
    material: "Brass casing",
    image: "/images/federal308.jpg",
    description:
      "Premium .308 Winchester ammunition designed for precision and hunting applications.",
    reviews: 80,
    SKU: "FED-308WIN-168GR",
    quantity: 50,
  },
  {
    id: 6,
    productName: "EOTech EXPS3 Holographic Sight",
    category: "Accessories",
    brand: "EOTech",
    price: 579.99,
    inStock: true,
    onSale: true,
    rating: 4.9,
    material: "Aluminum",
    image: "/images/eotech_exps3.jpg",
    description:
      "EOTech EXPS3 holographic sight provides fast target acquisition and reliability in all conditions.",
    reviews: 200,
    SKU: "EOT-EXPS3",
    quantity: 18,
  },
  {
    id: 7,
    productName: "Hornady Critical Defense 9mm",
    category: "Ammunition",
    brand: "Hornady",
    price: 19.99,
    inStock: true,
    onSale: false,
    rating: 4.8,
    caliber: "9mm",
    weight: "115gr",
    material: "Nickel-Plated Brass",
    image: "/images/hornady9mm.jpg",
    description:
      "Hornady Critical Defense is designed for personal protection and ensures consistent expansion.",
    reviews: 180,
    SKU: "HOR-CRD-9MM-115GR",
    quantity: 200,
  },
  {
    id: 8,
    productName: "Smith & Wesson M&P Shield 9mm",
    category: "Handgun",
    brand: "Smith & Wesson",
    price: 449.99,
    inStock: true,
    onSale: false,
    rating: 4.7,
    caliber: "9mm",
    weight: "620g",
    material: "Polymer",
    image: "/images/swmp9.jpg",
    description:
      "The M&P Shield offers a lightweight, slim profile for easy concealed carry.",
    reviews: 120,
    SKU: "SW-MP9-9MM",
    quantity: 30,
  },
]

export const categoriesCard = [
  {
    id: 1,
    Image: "/assets/images/coboygunbg.png",
    name: "Coboy Guns",
    },
    {
      id: 2,
      Image: "/assets/images/glock-removebg-preview.png",
      name: "Glock Gun",
      },
      {
        id: 3,
        Image: "/assets/images/ak1-removebg-preview.png",
        name: "AK-Gun",
        },
        {
          id: 4,
          Image: "/assets/images/savage.jpg",
          name: "Savage Gun",
          },
          {
            id: 5,
            Image: "/assets/images/ak7-removebg-preview.png",
            name: "AK- Gun",
            },

            {
              id: 6,
              Image: "/assets/images/b1.jpg",
              name: "Bullet",
              },
              {
                id: 7,
                Image: "/assets/images/ak7-removebg-preview.png",
                name: "AK-47",
                },
    
                {
                  id: 8,
                  Image: "/assets/images/b1.jpg",
                  name: "Bullet",
                  }
]

export const featuredCard = [
  {
    id: 1,
    image: "/assets/images/ak5-removebg-preview.png",
    span: "HOT",
    button: "Add to Cart",
    rate: "/assets/icons/Rating Group.svg",
    name: "AK-47",
    description: "A befit raffle",
    price: "$400.00",
  },
  {
    id: 2,
    image: "/assets/images/coboygunbg.png",
    span: "HOT",
    button: "Add to Cart",
    rate: "/assets/icons/Rating Group.svg",
    name: "Coboy Gun",
    description: "A short gun",
    price: "$300.00",
  },
  {
    id: 3,
    image: "/assets/images/glock-removebg-preview.png",
    span: "HOT",
    button: "Add to Cart",
    rate: "/assets/icons/Rating Group.svg",
    name: "Glock",
    description: "A hand gun",
    price: "$200.00",
  },
  {
    id: 4,
    image: "/assets/images/ak7-removebg-preview.png",
    span: "HOT",
    button: "Add to Cart",
    rate: "/assets/icons/Rating Group.svg",
    name: "Pistol Gun",
    description: "A good metals gun with bullet",
    price: "$100.00",
  },
]

export const shopCard =[
  {
    id: "1",
    image: "/assets/images/glock-removebg-preview.png",
    name: "Glock",
    link: "Collections",
  },
  {
    id: "2",
    image: "/assets/images/ak7-removebg-preview.png",
    name: "Pistol Gun",
    link: "Collections",
  },
]
